"""add tier1_business_user_commission to UserTransaction

Revision ID: 02024f9811a7
Revises: dfb178eb7dcc
Create Date: 2026-02-17 09:18:34.026053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02024f9811a7'
down_revision = 'dfb178eb7dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier1_business_user_referral_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tier1_business_user_commission', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.drop_column('tier1_business_user_commission')
        batch_op.drop_column('tier1_business_user_referral_id')

    # ### end Alembic commands ###
