"""Add is_suspended column to User

Revision ID: 059757bb5912
Revises: 4a4ee0d08c07
Create Date: 2026-02-01 20:56:19.314702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059757bb5912'
down_revision = '4a4ee0d08c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_suspended')

    # ### end Alembic commands ###
