"""Add awaiting_payment flag to Interaction

Revision ID: 0d85ede88edf
Revises: 768528849b89
Create Date: 2026-02-11 16:37:17.431546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d85ede88edf'
down_revision = '768528849b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('awaiting_payment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_column('awaiting_payment')

    # ### end Alembic commands ###
