"""add user_sponsor_id to business

Revision ID: 2315249de284
Revises: f408a5c484c4
Create Date: 2026-02-15 17:12:15.904569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2315249de284'
down_revision = 'f408a5c484c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_sponsor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_sponsor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_sponsor_id')

    # ### end Alembic commands ###
