"""Add transaction_id field to UserTransaction and BusinessTransaction

Revision ID: 395c3c4e9a0d
Revises: 0d85ede88edf
Create Date: 2026-02-14 12:04:17.343782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395c3c4e9a0d'
down_revision = '0d85ede88edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=48), nullable=False))
        batch_op.create_index(batch_op.f('ix_business_transaction_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=48), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_transaction_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_transaction_transaction_id'))
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_transaction_transaction_id'))
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
