"""Add Role and UserRoles tables

Revision ID: 4a4ee0d08c07
Revises: 
Create Date: 2026-02-01 19:53:28.843661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4ee0d08c07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('business_email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_code', sa.String(length=16), nullable=True),
    sa.Column('profile_photo', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('hours_of_operation', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('about_us', sa.Text(), nullable=True),
    sa.Column('service_1', sa.String(length=100), nullable=True),
    sa.Column('service_2', sa.String(length=100), nullable=True),
    sa.Column('service_3', sa.String(length=100), nullable=True),
    sa.Column('service_4', sa.String(length=100), nullable=True),
    sa.Column('service_5', sa.String(length=100), nullable=True),
    sa.Column('service_6', sa.String(length=100), nullable=True),
    sa.Column('service_7', sa.String(length=100), nullable=True),
    sa.Column('service_8', sa.String(length=100), nullable=True),
    sa.Column('service_9', sa.String(length=100), nullable=True),
    sa.Column('service_10', sa.String(length=100), nullable=True),
    sa.Column('search_keywords', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_email'),
    sa.UniqueConstraint('business_name'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_code', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('profile_photo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('business')
    # ### end Alembic commands ###
