"""add status field to Business

Revision ID: 527e5a4ae70c
Revises: 059757bb5912
Create Date: 2026-02-04 14:29:31.354438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527e5a4ae70c'
down_revision = '059757bb5912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        pass  # Nothing to do here, but this avoids IndentationError
    #   batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
    #   batch_op.add_column(sa.Column('draft_business_name', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_category', sa.String(length=50)))
    #   batch_op.add_column(sa.Column('draft_profile_photo', sa.String(length=200)))
    #   batch_op.add_column(sa.Column('draft_phone_number', sa.String(length=30)))
    #   batch_op.add_column(sa.Column('draft_address', sa.String(length=255)))
    #   batch_op.add_column(sa.Column('draft_latitude', sa.Float))
    #   batch_op.add_column(sa.Column('draft_longitude', sa.Float))
    #   batch_op.add_column(sa.Column('draft_hours_of_operation', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_website_url', sa.String(length=255)))
    #   batch_op.add_column(sa.Column('draft_about_us', sa.Text))
    #   batch_op.add_column(sa.Column('draft_service_1', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_service_2', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_service_3', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_service_4', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_service_5', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_service_6', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_service_7', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_service_8', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_service_9', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_service_10', sa.String(length=100)))
    #   batch_op.add_column(sa.Column('draft_search_keywords', sa.String(length=500)))


    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('draft_business_name')
        batch_op.drop_column('draft_category')
        batch_op.drop_column('draft_profile_photo')
        batch_op.drop_column('draft_phone_number')
        batch_op.drop_column('draft_address')
        batch_op.drop_column('draft_latitude')
        batch_op.drop_column('draft_longitude')
        batch_op.drop_column('draft_hours_of_operation')
        batch_op.drop_column('draft_website_url')
        batch_op.drop_column('draft_about_us')
        batch_op.drop_column('draft_service_1')
        batch_op.drop_column('draft_service_2')
        batch_op.drop_column('draft_service_3')
        batch_op.drop_column('draft_service_4')
        batch_op.drop_column('draft_service_5')
        batch_op.drop_column('draft_service_6')
        batch_op.drop_column('draft_service_7')
        batch_op.drop_column('draft_service_8')
        batch_op.drop_column('draft_service_9')
        batch_op.drop_column('draft_service_10')
        batch_op.drop_column('draft_search_keywords')
        batch_op.drop_column('status')  # only if you want to drop status as well

    # ### end Alembic commands ###
