"""add business_referral_id to UserTransaction

Revision ID: 58d109ec94bd
Revises: c8617648afad
Create Date: 2026-02-15 19:00:26.663828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d109ec94bd'
down_revision = 'c8617648afad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_referral_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.drop_column('business_referral_id')

    # ### end Alembic commands ###
