"""Add fields for featured businesses

Revision ID: 5feb9e5c5d4e
Revises: f3d42f1fa680
Create Date: 2026-02-20 19:46:29.000643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5feb9e5c5d4e'
down_revision = 'f3d42f1fa680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rank', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('manual_feature', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('manual_feature')
        batch_op.drop_column('rank')
        batch_op.drop_column('featured')

    # ### end Alembic commands ###
