"""add starter_html to Theme model

Revision ID: 635ced00de98
Revises: f4bf9188792c
Create Date: 2026-02-22 19:36:55.111453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635ced00de98'
down_revision = 'f4bf9188792c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starter_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.drop_column('starter_html')

    # ### end Alembic commands ###
