"""Your descriptive migration message

Revision ID: 6bfab8b32088
Revises: adb5ee52e0fa
Create Date: 2026-02-10 16:03:27.500591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfab8b32088'
down_revision = 'adb5ee52e0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.alter_column('interaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.alter_column('interaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.alter_column('interaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.alter_column('interaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
