"""add ad_fee field to BusinessTransaction

Revision ID: 6d30655e896c
Revises: 02024f9811a7
Create Date: 2026-02-17 17:20:10.257326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d30655e896c'
down_revision = '02024f9811a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('ad_fee')

    # ### end Alembic commands ###
