"""add ad_fee field to BusinessTransaction

Revision ID: 6d8cc23ad8c3
Revises: 6d30655e896c
Create Date: 2026-02-17 17:24:12.645375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8cc23ad8c3'
down_revision = '6d30655e896c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.drop_column('ad_fee')

    # ### end Alembic commands ###
