"""Add account_balance field to Business

Revision ID: 768528849b89
Revises: 6bfab8b32088
Create Date: 2026-02-11 13:13:05.168508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768528849b89'
down_revision = '6bfab8b32088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_balance', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('account_balance')

    # ### end Alembic commands ###
