"""Add social media fields to Business

Revision ID: 8e441f947d88
Revises: e85d4867ba89
Create Date: 2026-02-26 11:33:55.299392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e441f947d88'
down_revision = 'e85d4867ba89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('business_owner_id_fkey'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('business_owner_id_fkey'), 'user', ['owner_id'], ['id'])
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('facebook_url')

    # ### end Alembic commands ###
