"""Add interaction_id to UserTransaction and BusinessTransaction

Revision ID: adb5ee52e0fa
Revises: 989d4c7bffaf
Create Date: 2026-02-10 15:32:35.370425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb5ee52e0fa'
down_revision = '989d4c7bffaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interaction_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'interaction', ['interaction_id'], ['id'])

    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interaction_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'interaction', ['interaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('interaction_id')

    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('interaction_id')

    # ### end Alembic commands ###
