"""add invite table

Revision ID: b76b0930cbda
Revises: 395c3c4e9a0d
Create Date: 2026-02-15 15:25:04.029384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b76b0930cbda'
down_revision = '395c3c4e9a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invites')
    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.drop_column('business_name')

    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('business_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    op.create_table('invites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inviter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inviter_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('invitee_email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('invitee_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('referral_code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('accepted_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accepted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('invites_pkey'))
    )
    # ### end Alembic commands ###
