"""add business_referral_id to user_transaction

Revision ID: c8617648afad
Revises: 2315249de284
Create Date: 2026-02-15 18:26:07.309747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8617648afad'
down_revision = '2315249de284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_referral_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('business_referral_id')

    # ### end Alembic commands ###
