"""Add approved_by to business

Revision ID: d1ab37dede25
Revises: 5feb9e5c5d4e
Create Date: 2026-02-21 13:19:44.045127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ab37dede25'
down_revision = '5feb9e5c5d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['approved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approved_by')

    # ### end Alembic commands ###
