"""add user business commission fields to UserTransaction

Revision ID: dfb178eb7dcc
Revises: 58d109ec94bd
Create Date: 2026-02-16 21:16:39.102106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb178eb7dcc'
down_revision = '58d109ec94bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier2_business_user_referral_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tier2_business_user_commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tier3_business_user_referral_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tier3_business_user_commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tier4_business_user_referral_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tier4_business_user_commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tier5_business_user_referral_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('tier5_business_user_commission', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_transaction', schema=None) as batch_op:
        batch_op.drop_column('tier5_business_user_commission')
        batch_op.drop_column('tier5_business_user_referral_id')
        batch_op.drop_column('tier4_business_user_commission')
        batch_op.drop_column('tier4_business_user_referral_id')
        batch_op.drop_column('tier3_business_user_commission')
        batch_op.drop_column('tier3_business_user_referral_id')
        batch_op.drop_column('tier2_business_user_commission')
        batch_op.drop_column('tier2_business_user_referral_id')

    # ### end Alembic commands ###
