"""Add business_registration_doc to Business

Revision ID: f3d42f1fa680
Revises: 6d8cc23ad8c3
Create Date: 2026-02-18 19:34:22.536762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d42f1fa680'
down_revision = '6d8cc23ad8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_registration_doc', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('business_registration_doc')

    # ### end Alembic commands ###
