"""add invite table

Revision ID: f408a5c484c4
Revises: b76b0930cbda
Create Date: 2026-02-15 15:33:47.585437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f408a5c484c4'
down_revision = 'b76b0930cbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('inviter_type', sa.String(length=16), nullable=False),
    sa.Column('invitee_email', sa.String(length=200), nullable=False),
    sa.Column('invitee_type', sa.String(length=16), nullable=False),
    sa.Column('referral_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('accepted_id', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite')
    # ### end Alembic commands ###
