"""add or update business/ecommerce models

Revision ID: f4bf9188792c
Revises: d1ab37dede25
Create Date: 2026-02-21 22:38:48.662144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4bf9188792c'
down_revision = 'd1ab37dede25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('css_url', sa.String(length=150), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_slug', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('theme_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('custom_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('grapesjs_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_ecommerce_store', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['store_slug'])
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'theme', ['theme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('has_ecommerce_store')
        batch_op.drop_column('stripe_account_id')
        batch_op.drop_column('grapesjs_html')
        batch_op.drop_column('custom_html')
        batch_op.drop_column('theme_id')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('store_slug')

    op.drop_table('product')
    op.drop_table('theme')
    # ### end Alembic commands ###
