"""Add user/business transaction models

Revision ID: faa60dc21b85
Revises: 242f48fb2fc3
Create Date: 2026-02-08 20:39:48.229657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'faa60dc21b85'
down_revision = '242f48fb2fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('business_referral_id', sa.String(length=32), nullable=False),
    sa.Column('cash_back', sa.Float(), nullable=False),
    sa.Column('tier2_business_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier2_commission', sa.Float(), nullable=False),
    sa.Column('tier3_business_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier3_commission', sa.Float(), nullable=False),
    sa.Column('tier4_business_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier4_commission', sa.Float(), nullable=False),
    sa.Column('tier5_business_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier5_commission', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_referral_id', sa.String(length=32), nullable=False),
    sa.Column('cash_back', sa.Float(), nullable=False),
    sa.Column('tier2_user_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier2_commission', sa.Float(), nullable=False),
    sa.Column('tier3_user_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier3_commission', sa.Float(), nullable=False),
    sa.Column('tier4_user_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier4_commission', sa.Float(), nullable=False),
    sa.Column('tier5_user_referral_id', sa.String(length=32), nullable=False),
    sa.Column('tier5_commission', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('business_transactions')
    op.drop_table('user_transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('user_referral_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('cash_back', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('tier2_user_referral_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('tier2_commission', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('tier3_user_referral_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('tier3_commission', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('tier4_user_referral_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('tier4_commission', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('tier5_user_referral_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('tier5_commission', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_transactions_pkey'))
    )
    op.create_table('business_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('business_referral_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('cash_back', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('tier2_business_referral_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('tier2_commission', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('tier3_business_referral_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('tier3_commission', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('tier4_business_referral_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('tier4_commission', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('tier5_business_referral_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('tier5_commission', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('business_transactions_pkey'))
    )
    op.drop_table('user_transaction')
    op.drop_table('business_transaction')
    # ### end Alembic commands ###
